=== Jose-ant-1/lenguaje-de-marca/tema4/4.3/assets/restaurante.dtd
<!ELEMENT restaurante (menu,recetas,clientes)>
<!--Normas de menÃº-->
<!ELEMENT menu (platosMenu+)>
<!ELEMENT platosMenu (platoMenu+)>
<!ELEMENT platoMenu (nombrePlato,listaIngredientes,precio)>
<!ELEMENT nombrePlato (#PCDATA)>
    <!ATTLIST nombrePlato categoria CDATA #REQUIRED>
<!ELEMENT listaIngredientes (ingredienteMenu+)>
<!ELEMENT ingredienteMenu (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
    <!ATTLIST precio moneda (USD|EUR|GBP) #REQUIRED>
<!--Normas de recetas-->
<!ELEMENT recetas (receta+)>
<!ELEMENT receta (nombreReceta,ingredientes,proceso)>
<!ELEMENT nombreReceta (#PCDATA)>
    <!ATTLIST nombreReceta comensal (adulto|ninyo) #REQUIRED>
<!ELEMENT ingredientes (ingrediente+)>
<!ELEMENT ingrediente (nombreIngrediente+)>
<!ELEMENT nombreIngrediente (#PCDATA)>
    <!ATTLIST nombreIngrediente cantidad CDATA #REQUIRED>
<!ELEMENT proceso (paso+)>
<!ELEMENT paso (#PCDATA)>
<!--Normas de clientes-->
<!ELEMENT clientes (cliente+)>
<!ELEMENT cliente (nombreCliente,telefono,correo,pedidos)>
<!ELEMENT nombreCliente (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>
<!ELEMENT correo (#PCDATA)>
<!ELEMENT pedidos (pedido+)>
<!ELEMENT pedido (fecha,platos+)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT platos (plato+)>
<!ELEMENT plato (#PCDATA)>

=== Jose-ant-1/lenguaje-de-marca/tema4/dtd/4.3/restaurante.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE restaurante SYSTEM "./assets/restaurante.dtd">

<restaurante>
    <menu>
        <platosMenu>
            <platoMenu>
                <nombrePlato categoria="entrante"></nombrePlato>
                <listaIngredientes>
                    <ingredienteMenu></ingredienteMenu>
                    <ingredienteMenu></ingredienteMenu>
                    <ingredienteMenu></ingredienteMenu>
                </listaIngredientes>
                <precio moneda="EUR"></precio>
            </platoMenu>

            <platoMenu>
                <nombrePlato categoria="Bebida"></nombrePlato>
                <listaIngredientes>
                    <ingredienteMenu></ingredienteMenu>
                    <ingredienteMenu></ingredienteMenu>
                    <ingredienteMenu></ingredienteMenu>
                </listaIngredientes>
                <precio moneda="EUR"></precio>
            </platoMenu>        
        </platosMenu>
    </menu>
    

    <recetas>
        <receta>
            <nombreReceta comensal="adulto"></nombreReceta>
            <ingredientes>
                <ingrediente>
                   <nombreIngrediente cantidad=""></nombreIngrediente>
                </ingrediente>
            </ingredientes>
            <proceso>
                <paso></paso>
                <paso></paso>
                <paso></paso>
            </proceso>    
        </receta>

        <receta>
            <nombreReceta comensal="adulto"></nombreReceta>
            <ingredientes>
                <ingrediente>
                    <nombreIngrediente cantidad=""></nombreIngrediente>
                </ingrediente>
            </ingredientes>
            <proceso>
                <paso></paso>
                <paso></paso>
                <paso></paso>
            </proceso>    
        </receta>
    </recetas>


    <clientes>
        <cliente>
            <nombreCliente></nombreCliente>
            <telefono></telefono>
            <correo></correo>
            <pedidos>
                <pedido>
                    <fecha></fecha>
                    <platos>
                        <plato></plato>
                        <plato></plato>
                    </platos>
                </pedido>
            </pedidos>
        </cliente>

        <cliente>
            <nombreCliente></nombreCliente>
            <telefono></telefono>
            <correo></correo>
            <pedidos>
                <pedido>
                    <fecha></fecha>
                    <platos>
                        <plato></plato>
                        <plato></plato>
                    </platos>
                </pedido>
            </pedidos>
        </cliente>
    </clientes>
</restaurante>

=== Jose-ant-1/lenguaje-de-marca/tema4/4.3/restaurante.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
<!DOCTYPE restaurante SYSTEM "./assets/restaurante.dtd">

-->
<!DOCTYPE restaurante>
<restaurante>
    <menu>
        <platos>
            <plato>
                <nombre categoria="entrante"></nombre>
                <listaIngredientes>
                    <ingredientes></ingredientes>
                    <ingredientes></ingredientes>
                    <ingredientes></ingredientes>
                </listaIngredientes>
                <precio></precio>
            </plato>
            <plato>
                <nombre categoria="Bebida"></nombre>
                <listaIngredientes>
                    <ingredientes></ingredientes>
                    <ingredientes></ingredientes>
                    <ingredientes></ingredientes>
                </listaIngredientes>
                <precio></precio>
            </plato>        
        </platos>
    </menu>
    
    <recetas>
        <receta>
            <nombre comensal="adulto"></nombre>
            <ingredientes>
                <ingrediente>
                    <nombre cantidad="200gm"></nombre>
                </ingrediente>
                <ingrediente></ingrediente>
                <ingrediente></ingrediente>
            </ingredientes>
            <proceso>
                <paso></paso>
                <paso></paso>
                <paso></paso>
            </proceso>    
        </receta>
                <receta>
            <nombre comensal="adulto"></nombre>
            <ingredientes>
                <ingrediente>
                    <nombre cantidad="200gm"></nombre>
                </ingrediente>
                <ingrediente></ingrediente>
                <ingrediente></ingrediente>
            </ingredientes>
            <proceso>
                <paso></paso>
                <paso></paso>
                <paso></paso>
            </proceso>    
        </receta>
    </recetas>
    <clientes>
        <cliente>
            <nombre></nombre>
            <telefono></telefono>
            <correo></correo>
            <pedidos>
                <pedido>
                    <fecha></fecha>
                    <platos>
                        <plato></plato>
                        <plato></plato>
                    </platos>
                </pedido>
            </pedidos>
        </cliente>
        <cliente>
            <nombre></nombre>
            <telefono></telefono>
            <correo></correo>
            <pedidos>
                <pedido>
                    <fecha></fecha>
                    <platos>
                        <plato></plato>
                        <plato></plato>
                    </platos>
                </pedido>
            </pedidos>
        </cliente>
    </clientes>



</restaurante>
